### ISSUE TITLE
Cannot retrieve genome from BioProject accession, Same as issue #132

### ISSUE THREAD

**Issue by YZLong** [ncbi/datasets#170]
I got same problem as issue #132 with bioproject number: PRJNA756388, PRJNA187139, PRJNA400134

**Comment by ericcox1** [comment]
Hi Yuzhou,

Thanks for your feedback. In this case, the datasets command-line tool doesn't return any data because there are no [NCBI Assembly](https://www.ncbi.nlm.nih.gov/assembly/) records associated with the BioProject accessions that you provided: PRJNA756388, PRJNA187139, and PRJNA400134

The commands `summary genome accession` and `download genome accession` can be used with either an Assembly accession or a BioProject accession to return genome data associated with an NCBI Assembly record.

PRJNA756388, PRJNA187139, PRJNA400134 are all associated with sequencing reads in SRA and SRA data is not yet available through Datasets. 

I hope that helps.

Best,
Eric
