### ISSUE TITLE
datasets summary genome --limit all only lists 1,000 results

### ISSUE THREAD

**Issue by erinyoung** [ncbi/datasets#204]
I am trying to access all the organisms for all the genomes in bioproject PRJNA288601. There are ~13,713 assemblies in this bioproject at the time of this issue.

It seems, however, that I'm only able to get a summary for 1,000 of these samples. Is there a way to increase how many results I get?

This is what I've tried:

```
# default
$ datasets summary genome accession PRJNA288601 --as-json-lines | wc -l
1000

# specifying all
$  datasets summary genome accession PRJNA288601 --as-json-lines --limit all | wc -l
1000

# trying to up the limit
$ datasets summary genome accession PRJNA288601 --as-json-lines --limit 13713 | wc -l
1000
```

**Comment by ericcox1** [comment]
Hi @erinyoung,

Thanks for the bug report. I was able to reproduce this bug. Unfortunately, I'm not aware of any way to increase the number of results at the moment. Our development team will get started on a fix soon and I will post to this thread when the fix is ready.

Best,
Eric

Eric Cox, PhD [Contractor] (he/him/his)
NCBI Datasets
Sequence Enhancements, Tools and Delivery (SeqPlus)
NIH/NLM/NCBI
[eric.cox@nih.gov](mailto:eric.cox@nih.gov)

**Comment by ericcox1** [comment]
Hi @erinyoung,

This bug has been fixed.

You should no longer be limited to 1,000 results.

Here's the result I see for the BioProject you provided:
```
datasets summary genome accession PRJNA288601 --as-json-lines | wc -l
9244
```

Thanks again for the report!

Best,
Eric

**Comment by erinyoung** [comment]
Thank you!
