### ISSUE TITLE
Documentation links from v2 to v1

### ISSUE THREAD

**Issue by corneliusroemer** [ncbi/datasets#230]
On the v2 doc website: https://www.ncbi.nlm.nih.gov/datasets/docs/v2/languages/ you link to v1 for Python documentation, which doesn't make sense, it should link to v2 Python docs - do they exist?

The [Python](https://www.ncbi.nlm.nih.gov/datasets/docs/v1/languages/python/) link links here: https://www.ncbi.nlm.nih.gov/datasets/docs/v1/languages/python/ - note the v1 in the URL

<img width="1122" alt="image" src="https://user-images.githubusercontent.com/25161793/236004193-5119a643-ea76-4aeb-b994-956dd5c7b3f0.png">

**Comment by ericcox1** [comment]
Hi @corneliusroemer,

Thanks for opening this issue. The v2 Python docs do not exist because there are some updates we need to make to our Python library to support v2. I'll make a note to make this documentation page clearer.

-Eric

Eric Cox, PhD [Contractor] (he/him/his)
NCBI Datasets
Sequence Enhancements, Tools and Delivery (SeqPlus)
NIH/NLM/NCBI
[eric.cox@nih.gov](mailto:eric.cox@nih.gov)

**Comment by ericcox1** [comment]
Hi @corneliusroemer,

We have updated the v2 programming [languages page](https://www.ncbi.nlm.nih.gov/datasets/docs/v2/languages/) to clarify that the Datasets Python library only supports API v1 and not v2alpha.

Thanks again for your feedback.

Best,
Eric

Eric Cox, PhD [Contractor] (he/him/his)
NCBI Datasets
Sequence Enhancements, Tools and Delivery (SeqPlus)
NIH/NLM/NCBI
[eric.cox@nih.gov](mailto:eric.cox@nih.gov)
