### ISSUE TITLE
Unable to download all RefSeq genomes for a single bacterial species

### ISSUE THREAD

**Issue by rfm-targa** [ncbi/datasets#265]
Greetings!

Thank you for working on this tool; it has been essential to download huge datasets fast.
I am trying to download all RefSeq genome assemblies for several bacterial species. To do that, I am running the following command:

```
datasets download genome taxon "<species_name>" --assembly-source "RefSeq"
```

I have tried to download the genome assemblies for _Streptococcus pyogenes_, _Staphylococcus aureus_, _Streptococcus agalactiae_ and _Arcobacter butzleri_. The first attempts failed with one of the following errors:

```
Error: [gateway] Gateway Error (500 Internal Server Error)
```

or

```
Error: Internal error (invalid zip archive). Please try again
```

After the first attempts, I downloaded the genome assemblies for _Streptococcus pyogenes_, _Streptococcus agalactiae_ and _Arcobacter butzleri_. It is an intermittent issue; most of the time, it does not work. I thought it might be related to the number of genome assemblies, failing when requesting thousands of assemblies, but _Arcobacter butzleri_ only has 182. I am using `datasets version: 15.16.2`.
Any insight into this would be appreciated.

Best regards,

Rafael

**Comment by syntheticgio** [comment]
Hi Rafael,

I'd like to gather a little more information if possible.  Has this been a problem over the past few days or have you noticed it from before then?

Thanks!
John

**Comment by syntheticgio** [comment]
Thanks for the follow up.  First let me apologize that you've experienced this recently.  Over the past week we've had some internal issues we've been resolving.  At this point you shouldn't see this issue any longer.  However over the next week there are some other changes we're making internally to attempt to prevent this from happening.  It is possible there are a few intermittent hiccups during that time (although we're trying to avoid it!).

If you end up noticing this issue in the future (lets say after next week) please feel free to open a new report.  We actively monitor for these types of issues but we very much appreciate the community engagement since it is always possible something is flying under the radar!

I'd also like to take the opportunity to encourage you to share any additional feedback (either via github issues or on the datasets website), especially related to pain points or requested features.  We love to hear about how researchers are using the tools and how we can improve them further to get some of the logistics out of the way of the science!
