### ISSUE TITLE
can not retrieve PRJNA822777 with datasets 15.25.0

### ISSUE THREAD

**Issue by mmarchywka** [ncbi/datasets#281]
I just downloaded this and tried the Sanger example which worked but this fails,

`./datasets --version
datasets version: 15.25.0
marchywka@happy:/home/ubuntu/dev/ncbi$ ./datasets summary genome accession PRJNA822777 
{"total_count": 0}
`

even though it is there on the web site and I can see it with my eutilsutility,

` eutilsnew -db sra -v -out xxx PRJNA822777
Count is 136 versus 136
--2023-10-31 16:38:22--  https://eutils.ncbi.nlm.nih.gov/entrez/eutils/efetch.fcgi?tool=biotechmarchywka&email=marchywka@hotmail.com&rettype=abstract&retmode=text&retstart=0&retmax=136&db=sra&query_key=1&WebEnv=MCID_654165bdf484664ffc2bcf57
Resolving eutils.ncbi.nlm.nih.gov (eutils.ncbi.nlm.nih.gov)... 130.14.29.110, 2607:f220:41e:4290::110
Connecting to eutils.ncbi.nlm.nih.gov (eutils.ncbi.nlm.nih.gov)|130.14.29.110|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: unspecified [text/xml]
Saving to: ‘STDOUT’

-                       [           <=>      ]   1.08M   218KB/s    in 5.0s    

2023-10-31 16:38:27 (223 KB/s) - written to stdout [1133169]
`

**Comment by ericcox1** [comment]
Hi @mmarchywka,

Thanks for opening this issue.

>I just downloaded this and tried the Sanger example which worked but this fails

`datasets summary genome accession` is used to get genome metadata for assembled genomes. 
The [Sanger example](https://www.ncbi.nlm.nih.gov/datasets/docs/v2/how-tos/genomes/get-genome-metadata/#using-bioproject-accession), `PRJEB33226`, is associated with 54 assembled genomes, so 
`datasets summary genome accession PRJEB33226` will return metadata for these 54 assemblies.

On the other hand, `PRJNA822777` is not expected to work because there are no assembled genomes associated with this BioProject. I'll make a note for us to add a helpful error message that explains why we don't return any data for cases like this.

I hope that helps.

Best,
Eric

Eric Cox, PhD [Contractor] (he/him/his)
NCBI Datasets
Sequence Enhancements, Tools and Delivery (SeqPlus)
NIH/NLM/NCBI
[eric.cox@nih.gov](mailto:eric.cox@nih.gov)
