### ISSUE TITLE
server error with a large number of accessions

### ISSUE THREAD

**Issue by jvolkening** [ncbi/datasets#296]
I have a file of ~ 89k bacterial assembly accessions. When using the following command:
```bash
datasets download genome accession --dehydrated --inputfile accs.txt
```
I get the following error:
```
Error: [gateway] Internal Server Error (For more help, see the NCBI Datasets Documentation at https://www.ncbi.nlm.nih.gov/datasets/docs/) (982DE3CF3898E9F8561F47E6.3.1)
```
A little trial and error suggests ~65k accessions as the upper limit of what I can input without getting an error. I tried both `head`ing and `tail`ing the file to make sure it wasn't a bad accession somewhat near the end, but got the same error with both. Of course, as a workaround I can chunk the accessions and do multiple downloads.

**Comment by syntheticgio** [comment]
Hi @jvolkening is there any way you can provide the accession list?  I'd like to try to replicate exactly what you've done.  That said you're probably correct that there is some issue around that level.  We haven't run into this with internal testing but are actually in the process of setting up stress testing related to this.  I'll replicate it and then try to get some priority added to the testing.  

In the interim it sounds like you're able to chunk to get around the issue which makes me believe you're not currently blocked in your research.  If this is true I'd like to pursue a proper fix internally instead of a quick fix to get you going :)

**Comment by jvolkening** [comment]
Here is the accession list used.

[accs.txt.gz](https://github.com/ncbi/datasets/files/13621834/accs.txt.gz)

> In the interim it sounds like you're able to chunk to get around the issue which makes me believe you're not currently blocked in your research. If this is true I'd like to pursue a proper fix internally instead of a quick fix to get you going :)

Yes, that's fine, thanks.

**Comment by xonq** [comment]
I am also getting this error with the following accession list, but it works with a file of two accessions:

[ncbi_accs.txt](https://github.com/ncbi/datasets/files/13745179/ncbi_accs.txt)

**Comment by ericcox1** [comment]
Thanks @xonq, I appreciate your feedback. We are going to try to fix this soon.

**Comment by LeandroD94** [comment]
Good evening!

I'm experiencing the same error... I'm trying to download the whole bacteria cds but I get the same error. The command works with the archaea (much lesser then bacteria) but not with the bacteria!
How to download them?

Thank you,
Leandro

**Comment by xonq** [comment]
@LeandroD94 I believe they are recommending to workaroynd by breaking your data into small enough processable chunks that proceed without error. I have been able to get 10-50k through at a time. 100k+ has triggered the error for me.

**Comment by syntheticgio** [comment]
This issue has been fixed, thanks for reporting the bug!  If you still run into problems please open a new issue.
