### ISSUE TITLE
How can I download all bacterial genes?

### ISSUE THREAD

**Issue by nettanetta** [ncbi/datasets#297]
Hi,
I am trying to use the datasets command line tool to download all bacterial genes.
I wanted to start by loading the summary file - I used `datasets summary gene taxon Bacteria --as-json-lines | dataformat tsv gene` and expected to get all bacterial genes. However, I got just 4360 genes, all of which are of Bacteroides fragilis.
What am I missing?
How can I download the metadata and sequences of all bacterial genes?
thanks!
Netta

**Comment by ericcox1** [comment]
Hi @nettanetta ,

Thanks for opening this issue. 

>However, I got just 4360 genes, all of which are of Bacteroides fragilis.

We are aware of this bug and we are releasing a fix today 😄 .

>I used datasets summary gene taxon Bacteria --as-json-lines | dataformat tsv gene and expected to get all bacterial genes
1. We don't support above-species taxa with the `gene` subcommand. (Our [documentation](https://www.ncbi.nlm.nih.gov/datasets/docs/v2/reference-docs/command-line/datasets/summary/gene/datasets_summary_gene_taxon/) on this is incorrect--I'll make a note to fix that)
2. Only a small subset of bacterial species are available using the `gene` subcommand, which gets data from NCBI Gene

Alternatively, you may want to start by downloading ~72.7 M CDS sequences annotated on the set of 17,694 reference bacterial genomes.

Since this is a large dataset (~80 GB), I would suggest using rehydration (documented [here](https://www.ncbi.nlm.nih.gov/datasets/docs/v2/how-tos/genomes/large-download/)): 
1. `datasets download genome taxon 2 --include cds --reference --assembly-source refseq --filename bacteria-cds.zip`
2. `unzip bacteria-cds.zip -d bacteria-cds`
3. `datasets rehydrate --directory bacteria-cds`

Please let me know if you have any other questions.

Best,
Eric

Eric Cox, PhD [Contractor] (he/him/his)
NCBI Datasets
Sequence Enhancements, Tools and Delivery (SeqPlus)
NIH/NLM/NCBI
[eric.cox@nih.gov](mailto:eric.cox@nih.gov)

**Comment by ericcox1** [comment]
The bug related to misinterpreting certain taxonomic names, including your example above, has been fixed. We are aware of a bug in the error message and we will try to fix that soon.

Thanks again.

-Eroc

**Comment by nettanetta** [comment]
Thank you for your quick response,
A dataset of ~72.7 M CDS sequences sounds like a great start for me. Will take your suggestion.
thanks
Netta
