### ISSUE TITLE
Should taxon_suggest endpoint return empty array in field instead of empty object?

### ISSUE THREAD

**Issue by manulera** [ncbi/datasets#312]
Hello,

First of all let me say that the datasets api is a great initiative and I love how much care is being put in the API docs, and the ability to test on the site, when compared to the entrez API.

For the `taxonomy/taxon_suggest` endpoint, when you write a query with results e.g. 

https://api.ncbi.nlm.nih.gov/datasets/v2alpha/taxonomy/taxon_suggest/pombe

You get a response like this:

```json
{
  "sci_name_and_ids": [
    {
      "sci_name": "Schizosaccharomyces pombe",
      "tax_id": "4896",
      "common_name": "fission yeast",
      "matched_term": "S. pombe",
      "rank": "SPECIES"
    }
  ]
}
```

When making a request like the one below that gives no result you get an empty object `{}`. Wouldn't it be more consistent to get something like this?:

https://api.ncbi.nlm.nih.gov/datasets/v2alpha/taxonomy/taxon_suggest/pombeeeeee

```json
{
  "sci_name_and_ids": []
}
```

**Comment by manulera** [comment]
Similarly, this endpoint:

https://api.ncbi.nlm.nih.gov/datasets/v2alpha/genome/accession/GCF_000002945.1/annotation_report?search_text=aaaaaaaaa

**Comment by syntheticgio** [comment]
Hi manulera.  The problem with returning 

```
{
  "sci_name_and_ids": []
}
```
instead of a blank object is that it implies that `pombeeeeee` exists, but there is no data for that particular field (others may be masked depending on the URL request).   This is pretty standard for how you return structures that are empty vs how you handle an error state (accession doesn't exist).  In other words, if there is an instance of it in our database "sci_name_and_ids" would exist but perhaps be empty.  If there isn't an instance in our database (i.e. accession doesn't exist) there are no fields available.  

Aside from some technical reasons why we wouldn't want to do this, there are some downstream ones.  Since information has to go through a process to be exposed on our website, this distinction is important for individuals that are waiting for their data to be published.  A blank object they know it hasn't been digested yet, the empty "sci_name_and_ids" would point to a problem with the data.  It is also important for 3rd party users (along with our front end) to be able to distinguish between these when returning an error message to the user.

Hopefully this helps.
John

**Comment by manulera** [comment]
Hi @syntheticgio, thanks for taking the time to reply with an explanation. Just a clarification, in case it is relevant. You raised the issue:

> it implies that `pombeeeeee` exists, but there is no data for that particular field (others may be masked depending on the URL request)

However, the url parameter in `/taxonomy/taxon_suggest/{taxon_query}` does not refer to a field in the requested object, nor an accession, it's an auto-complete query. Similarly, the other endpoint that I pasted in the next comment contains a "free text search query" parameter not intended to map to a field or identifier. For example if `annotation_report=ase`, it will return the gene `ase1`, and many others that contain the string `ase` in either of the annotation fields.

This is different from the stackoverflow example, where they are querying an exact match for an identifier. Returning null there would be equivalent to a 404 error if an accession string is wrong, which I understand.

I think a case like this is more similar to a python `re.findall` (which returns empty list if no matches) than a `string.find` kind of function. In terms of whether this is common practice for APIs, a call to the entrez esearch API with a query without results returns an empty array in the `idlist` field, where it would normally returned the matched ids, keeping the same object structure:

https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esearch.fcgi?db=taxonomy&term=dummy[WORD]&retmax=200&retmode=json

**Comment by syntheticgio** [comment]
Hi @manulera ,

You are correct that we _could_ have implemented it that way.  However, we've chosen not to return a 404 error with a non-null response body or a 200 HTTP request with a response body with an object that specified that it is empty (i.e. a non-null object with a field set to say 'there is nothing found').  I will mention it internally and will re-open the ticket if there is a decision to change this infrastructure.

Thanks,
John

**Comment by manulera** [comment]
Hi @syntheticgio thanks for considering and for the followup!
