### ISSUE TITLE
Versioning and backwards compatibility

### ISSUE THREAD

**Issue by muffato** [ncbi/datasets#324]
Hello.

Using an older CLI (just a few versions old) seems to work, but I always fear it will miss some data, especially because there are often major version bumps.

Can you explain how you do versioning and what I should expect in terms of backwards compatibility ?

Best regards,
Matthieu

**Comment by ericcox1** [comment]
Hi @muffato,

Thanks for opening this issue.

>Using an older CLI (just a few versions old) seems to work, but I always fear it will miss some data


In general, for CLI versions v14+, new records (e.g, a genome assembly) will be available. However, when we add new fields to a data report, you'll need to use the new version of the CLI to see those.

>Can you explain how you do versioning and what I should expect in terms of backwards compatibility ?

For versions v14+, you can expect backwards compatibility, _except_ when we introduce breaking changes. Since v14.0.0, we have only introduced a single breaking change so far (from the release [notes page](https://www.ncbi.nlm.nih.gov/datasets/docs/v2/reference-docs/release-notes/)):

>v15.0.0
BREAKING CHANGES
Features: Update v2alpha assembly report field from submission_date to release_date

Just a reminder, that CLI versions 13.x and lower will be deprecated in June retired in December 2024. For more information, see our recent [blog post](https://ncbiinsights.ncbi.nlm.nih.gov/2024/02/20/updates-ncbi-datasets-apis-command-line-tools/#more-12872).

Best,
Eric

Eric Cox, PhD [Contractor] (he/him/his)
NCBI Datasets
Sequence Enhancements, Tools and Delivery (SeqPlus)
NIH/NLM/NCBI
[eric.cox@nih.gov](mailto:eric.cox@nih.gov)

**Comment by muffato** [comment]
Thank you for the clear answer, @ericcox1 !
