### ISSUE TITLE
`ncbi_dataset/data/data_report.jsonl` sometimes missing

### ISSUE THREAD

**Issue by bernt-matthias** [ncbi/datasets#328]
When executing:

```
datasets download gene accession 'WP_004675351.1'   --include-flanks-bp 100   --include gene,protein --no-progressbar
dataformat tsv prok-gene --package ncbi_dataset.zip --fields accession,description,ec-number,gene-symbol,mapping-count,protein-length,protein-name > gene_data_report.tsv
```

I get `Error: no matching files found for [ncbi_dataset/data/data_report.jsonl]`

**Comment by ericcox1** [comment]
Hi @bernt-matthias,

Thanks for opening this issue. This is a known bug, where we don't return the data report for WP proteins that have been suppressed. [WP_004675351.1](https://www.ncbi.nlm.nih.gov/protein/WP_004675351.1?report=genpept)  was suppressed for the following reason: `This protein record was suppressed because it is no longer annotated on any genome`.

I'll bring this up with the team and I'll comment on this thread with any updates.

Best,
Eric
