### ISSUE TITLE
"dataformat does not recognize this input" error since August 17 (not before) on version 16.26.2

### ISSUE THREAD

**Issue by corneliusroemer** [ncbi/datasets#404]
**Describe the bug**

Version 16.26.2 was working well until around 9pm UTC on August 17 (around 12 hours ago at time of writing).

Since then, when running dataformat on dataset download results in an error: `dataformat doesn't recognize this input ... Error:  unknown field "usaState"`

**To Reproduce**

1. Install version 16.26.2 - you can use this docker container with it installed:
    ```
    docker run -it ghcr.io/loculus-project/ingest@sha256:2507b529cdf384f207f93c2bab4c0f9a49bf39577b15eed26ad60e8f88ebc756 /bin/bash
    ```
2. Download e.g. West Nile Virus datapackage:
    ```
    datasets download virus genome taxon 3048448 --no-progressbar --filename ncbi_dataset.zip
    ```
3. Run dataformat with default configs on this:
    ```
    dataformat tsv virus-genome --package ncbi_dataset.zip >metadata_post_extract.tsv
    ```
4. Observer results

Logs:

```
$ dataformat tsv virus-genome --package ncbi_dataset.zip >metadata_post_extract.tsv
dataformat doesn't recognize this input

For best results
1. Make sure to use --as-json-lines with the datasets command
2. Make sure that you're using the latest version of the datasets command line tool

Use --force to remove this warning.
Download the latest version of the datasets command line tool: https://www.ncbi.nlm.nih.gov/datasets/docs/v2/download-and-install
Error:  unknown field "usaState"
Usage
  dataformat tsv virus-genome [flags]
...SNIP...
```

**Workaround**

Upgrade to the latest version (16.29.0) seems to fix this. A look at its release notes shows an entry:
> A new "U.S. State" field has been added to the virus data reports, enabling users to filter virus genome summary and download requests using the two-letter state code (e.g., NY). For additional details, please see the [Virus Data Reports Documentation](https://www.ncbi.nlm.nih.gov/datasets/docs/v2/reference-docs/data-reports/virus/#ncbi-datasets-v2-reports-VirusAssembly-CollectionLocation).

It seems plausible that this addition causes the backwards incompatible breakage for dataformats when that field is present in the content received from the server.

**Comment by ericcox1** [comment]
Hi @corneliusroemer,

Thanks for your report. 

> It seems plausible that this addition causes the backwards incompatible breakage for dataformats when that field is present in the content received from the server.

That is correct.

We recommend updating both `dataformat` and `datasets` together to avoid this error.

Best,
Eric

**Comment by corneliusroemer** [comment]
I think there's a misunderstanding - this error is not due mismatch between datasets and dataformat. Both are at the same version.

It seems server side changes applied at the same time as the release of 16.29.0 broke dataformat for everyone who is not using the latest version.

It caused build failure in all Nextstrain ingest jobs, Pathoplexus etc.

It's a real breaking change for everyone who doesn't update to the latest version the second it's out.

Maybe I didn't make this clear enough in my issue report.

**Comment by ericcox1** [comment]
Hi @corneliusroemer,

Thanks for the clarification. You are correct, the new field is a breaking change when downloading a package using _datasets_ and then using _dataformat_ to generate a table. 

While we consider how we can avoid such breaking change when we add new fields in the future, here are a couple of options for working around this problem:

1. Update to the latest version of both _datasets_ and _dataformat_ (as you already figured out)
2. Use the `--force` flag with _dataformat_ to ignore the error. You could build this into your pipeline to ignore the error in the future. Please note that with the addition of new fields the order of columns in the table could be affected.
3. Use `datasets summary virus genome taxon 3048448 --as-json-lines | dataformat tsv virus-genome`. This avoids triggering the error because `datasets summary` does not pick up the new field.

Thanks again for your feedback.

Best,
Eric
