### ISSUE TITLE
Unable to download all CCHF sequences using datasets CLI

### ISSUE THREAD

**Issue by anna-parker** [ncbi/datasets#411]
**Describe the bug**
I am using the most recent version
```
datasets --version                                                                        
datasets version: 16.31.0
```

When I download taxonId 3052518 (CCHF) using the datasets cli I get only 3440 sequences, however NCBI virus shows that there are 4760 CCHF sequences: https://www.ncbi.nlm.nih.gov/labs/virus/vssi/#/virus?SeqType_s=Nucleotide&VirusLineage_ss=Orthonairovirus%20haemorrhagiae,%20taxid:3052518

**To Reproduce**

I am trying to download all CCHF sequences. I use the command 
```
datasets download virus genome taxon 3052518  --no-progressbar --filename results/ncbi_dataset.zip
```

However when I download the sequences there are only 3440.
```
unzip -jp results/ncbi_dataset.zip ncbi_dataset/data/genomic.fna > results/sequences.fasta
grep -c "^>" results/sequences.fasta 
```
returns 3440

I confirmed this is also the case for metadata

```
dataformat tsv virus-genome --package results/ncbi_dataset.zip > results/metadata_post_extract.tsv
tail -n +2 results/metadata_post_extract.tsv | wc -l
```
returns 3440 (ignoring the header). 

**Expected behavior**
I expect to download the same number of sequences that I also see on NCBI virus

**Comment by ericcox1** [comment]
Hi @anna-parker,

Thanks for opening this issue. 

It looks like there was a change to the taxonomy ID for the 1,320 sequence records missing from the _datasets_ query that you provided that caused the discrepancy between NCBI Datasets and NCBI Virus. We're working to get this fixed ASAP. I'll comment on this thread when the fix is ready.

Best,
Eric

Eric Cox, PhD [Contractor] (he/him/his)
NCBI Datasets
NIH/NLM/NCBI
[eric.cox@nih.gov](mailto:eric.cox@nih.gov)

**Comment by ericcox1** [comment]
Hi @anna-parker,

The virus sequence records have been updated and it looks like there is no longer a discrepancy between NCBI Datasets and NCBI Virus.

```
datasets summary virus genome taxon 3052518 --limit none
{"total_count": 4760}
```

Thanks again for opening this issue.

Best,
Eric

**Comment by anna-parker** [comment]
Thanks @ericcox1 for the quick response and fix!
