### ISSUE TITLE
How exactly works orthologs retrieval process? 

### ISSUE THREAD

**Issue by MauriAndresMU1313** [ncbi/datasets#416]
Before I opened an issue to ask for help to obtain orthologs from an unknown gene list for specific taxa, here is the line that I used:
```
datasets download gene accession --inputfile transcript_list-v1.tsv --ortholog mustelidae,hominidae,muridae,canidae --filename mustelidae_plus_ortholog_list.zip
```
Everything is fine, and I got the metadata associated with it, thanks to a member of this repository. Thank you again!

This post is not an issue or a request for a new feature, the intention is to understand better the way that the ```NCBI-dataset``` tool works to retrieve orthologs for a given gene list. 
My unknown gene list contains that like this:
```
XM_045082563.1
XM_004781206.3
XM_045078899.1
XM_045078939.1
XM_045078982.1
XM_045079143.1
XM_045079197.1
XM_045075315.1
XM_045075336.1
XM_045075373.1
```
Then, I can retrieve orthologs based on the families I specified in the ```--ortholog``` flag. After getting the data, I perform another filtering process, which is to filter the ```faa``` or ```fna``` based on my species of interest, all related to those families. Everything is okay so far. 
Here is where I need to understand how this works. If I open my sequences files, all the data is agglomerated together. I will use the example of ```Orthofinder``` which is a well-known tool for orthologs, and I mentioned in my last post. All the orthologs will be present in the same orthogroup. 
My question is how exactly does this tool perform that process? I would like to understand how because I would like to perform an extraction process to group all the sequences that are similar in orthogroups. I can not do that with ```Orthofinder``` because the tool input should be complete proteomes, so maybe if I create the orthogroups from the ```fna``` files retrieved with this tool, the results could not be accurate. 
So I'm thinking of performing an in-house script to perform this. If you wonder, what if the idea to use another tool to validate the orthologs, is because I would like to annotate unknown genes in my specie of interest using the orthogroup validation approach and the approach used with this tool. If I can perform this process, will be great to validate results using two different tools. 

Any comment, or explanation for the explanation of the ortholog's obtention data will be great and really appreciated!
Thank you!

**Comment by ericcox1** [comment]
Hi @MauriAndresMU1313,

>My unknown gene list contains that like this:

First of all, for the list of transcript accessions (XM_) you shared above, no orthologs have been calculated for the taxa you specified (mustelidae,hominidae,muridae,canidae). But I think we can leave that aside and assume that you have other transcript accessions not mentioned that _do_ have calculated orthologs.

>another tool to validate the orthologs

You might wan to check out some pre-calculated 3rd party resources. For example, _Mustela putorius furo_ is included in [OrthoDB](https://www.orthodb.org/?ncbi=101671927) and [OMA](https://omabrowser.org/oma/genome/MUSPF/info/).  You may need to convert IDs to retrieve ortholog groups from these resources.  NCBI Orthologs will be more conservative than these methods since we report only unambiguous reciprocal 1:1 ortholog pairs only.

>I would like to perform an extraction process to group all the sequences that are similar in orthogroups

Here's what I would suggest to get started:
1. Start with the 3-column table mentioned in https://github.com/ncbi/datasets/issues/412#issuecomment-2417270319
```
head -5 genes-ortho-proteins.tsv
100455260 2033 XP_009232690.4
100455260 2033 XP_009232691.4
100455260 2033 XP_054399489.2
100455260 2033 XP_054399490.2
100684945 2033 XP_038344445.1
```
2. Generate separate files of protein accessions for each ortholog ID using `awk`:
```
awk '{print$3>$2".list"}' genes-ortho-proteins.tsv
```
This will give you one file for each ortholog set, where the file name is the ortholog ID, containing protein accessions:
```
ls *.list
2033.list  440689.list

head -5 2033.list
XP_009232690.4
XP_009232691.4
XP_054399489.2
XP_054399490.2
XP_038344445.1
```
3. Then you can use [seqtk](https://github.com/lh3/seqtk) to generate separate protein sequence files, one per ortholog set:
```
seqtk subseq protein.faa 2033.list > 2033.faa

head -c 200 2033.faa
>XP_034372486.1 Ep300 [organism=Arvicanthis niloticus] [GeneID=117718741] [isoform=X1]
MAENVVEPGPPSAKRPKLSSPALSASASDGTDFGSLFDLEHDLPDELINSSELGLTNGGDISQLQTSLGIVPDAASKHKQLSELLRSGSSPNLNMGVGGPGQVMASQSQQNSP
```

Best,
Eric
