### ISSUE TITLE
GenBank assembly not available if  RefSeq is suppressed?

### ISSUE THREAD

**Issue by koolape** [ncbi/datasets#56]
Datasets reported an error while downloading assembly by RefSeq assembly accession:
`Some of the assemblies provided ('GCF_900706865.1') are valid NCBI Assembly Accessions,
but are not in scope for NCBI Datasets. `
Later I found that RefSeq is suppressed. So I tired downloading by its GenBank assembly accession. But still got an error:
`Some of the assemblies provided ('GCA_900706865.1') are valid NCBI Assembly Accessions,
but are not in scope for NCBI Datasets. `
Then I tried another accession `GCA_014207855.1` whose RefSeq assembly is not suppressed, and it worked fine.

**Comment by ericcox1** [comment]
Hi Koolape, Thanks for your feedback. GCA_900706865.1 was removed from Datasets because of an assembly quality issue, specifically, we identified many frameshifted coding sequences. We are currently reviewing our rules for inclusion in Datasets and feedback such as this is helpful. You can review information about which genome assemblies are included in Datasets here: https://www.ncbi.nlm.nih.gov/datasets/docs/reference-docs/genome-scope/

Best,
Eric

Eric Cox, PhD [Contractor] (he/him/his)
NCBI Datasets
Sequence Enhancements, Tools and Delivery (SeqPlus)
NIH/NLM/NCBI
eric.cox@nih.gov
